version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 3307
      DB_DATABASE: dzencodedb
      DB_USERNAME: root
      DB_PASSWORD: root



  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
#    environment:
#      REACT_APP_BACKEND_URL: http://backend:8000  # Set the URL to your Laravel backend
#    depends_on:
#      - backend
    tty: true

volumes:
  mysql_data: