version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www/html
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - app
